# Generated by Django 4.2.7 on 2023-12-05 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product_Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CategorieName", models.CharField(max_length=100)),
                ("Categorieid", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("PName", models.CharField(max_length=100)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("Pid", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("Date", models.DateField()),
                (
                    "CategorieName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.product_categories",
                    ),
                ),
            ],
        ),
    ]
